"""Add address and private_key to users

Revision ID: 3e31570301e5
Revises: 2ee482dc4985
Create Date: 2025-01-05 11:49:31.148109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e31570301e5'
down_revision: Union[str, None] = '2ee482dc4985'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('utilisateur', sa.Column('address', sa.String(), nullable=True))
    op.add_column('utilisateur', sa.Column('private_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('utilisateur', 'private_key')
    op.drop_column('utilisateur', 'address')
    # ### end Alembic commands ###
